# Generated by Django 6.0.3 on 2026-03-11 12:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InjuryCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_team', models.CharField(max_length=120)),
                ('away_team', models.CharField(max_length=120)),
                ('source', models.CharField(default='', max_length=60)),
                ('data', models.JSONField()),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Caché de bajas',
                'verbose_name_plural': 'Caché de bajas',
                'unique_together': {('home_team', 'away_team')},
            },
        ),
    ]
