# Generated by Django 6.0.3 on 2026-03-07 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('home_team', models.CharField(max_length=100)),
                ('away_team', models.CharField(max_length=100)),
                ('fthg', models.IntegerField(verbose_name='Full Time Home Goals')),
                ('ftag', models.IntegerField(verbose_name='Full Time Away Goals')),
                ('ftr', models.CharField(choices=[('H', 'Home Win'), ('D', 'Draw'), ('A', 'Away Win')], max_length=1, verbose_name='Full Time Result')),
            ],
            options={
                'verbose_name_plural': 'Matches',
                'ordering': ['-date'],
            },
        ),
    ]
