# Generated by Django 6.0.3 on 2026-03-07 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='ac',
            field=models.IntegerField(default=0, verbose_name='Away Corners'),
        ),
        migrations.AddField(
            model_name='match',
            name='af',
            field=models.IntegerField(default=0, verbose_name='Away Fouls'),
        ),
        migrations.AddField(
            model_name='match',
            name='ar',
            field=models.IntegerField(default=0, verbose_name='Away Red Cards'),
        ),
        migrations.AddField(
            model_name='match',
            name='as_shots',
            field=models.IntegerField(default=0, verbose_name='Away Shots'),
        ),
        migrations.AddField(
            model_name='match',
            name='ast',
            field=models.IntegerField(default=0, verbose_name='Away Shots on Target'),
        ),
        migrations.AddField(
            model_name='match',
            name='ay',
            field=models.IntegerField(default=0, verbose_name='Away Yellow Cards'),
        ),
        migrations.AddField(
            model_name='match',
            name='hc',
            field=models.IntegerField(default=0, verbose_name='Home Corners'),
        ),
        migrations.AddField(
            model_name='match',
            name='hf',
            field=models.IntegerField(default=0, verbose_name='Home Fouls'),
        ),
        migrations.AddField(
            model_name='match',
            name='hr',
            field=models.IntegerField(default=0, verbose_name='Home Red Cards'),
        ),
        migrations.AddField(
            model_name='match',
            name='hs',
            field=models.IntegerField(default=0, verbose_name='Home Shots'),
        ),
        migrations.AddField(
            model_name='match',
            name='hst',
            field=models.IntegerField(default=0, verbose_name='Home Shots on Target'),
        ),
        migrations.AddField(
            model_name='match',
            name='hy',
            field=models.IntegerField(default=0, verbose_name='Home Yellow Cards'),
        ),
    ]
